import menu from './modules/index/menu';
import smoothScroll from './modules/index/smoothScroll';
import modals from './modules/index/modals';
import phoneValidation from './modules/index/phoneValidation';
import test from './modules/index/test';
import sendForm from './modules/index/sendForm';
import renderServiceList from './modules/index/renderServiceList';
import accordeonFAQ from './modules/index/accordeonFAQ';
import successFormulaHints from './modules/index/successFormulaHints';
import repairTypesSlider from './modules/index/repairTypesSlider';
import portfolioSlider from './modules/index/portfolioSlider';
import contractSliderPopup from './modules/index/contractSliderPopup';
import rewievsSlider from './modules/index/rewievsSlider';

menu();
smoothScroll();
modals();
phoneValidation();
test();
sendForm();
renderServiceList();
accordeonFAQ();
successFormulaHints();
repairTypesSlider();
portfolioSlider();
contractSliderPopup();
rewievsSlider();
