import menu from './modules/menu';
import smoothScroll from './modules/smoothScroll';
import modals from './modules/modals';
import phoneValidation from './modules/phoneValidation';
import test from './modules/test';
import sendForm from './modules/sendForm';
import renderServiceList from './modules/renderServiceList';
import accordeonFAQ from './modules/accordeonFAQ';
import successFormulaHints from './modules/successFormulaHints';
import repairTypesSlider from './modules/repairTypesSlider';
import portfolioSlider from './modules/portfolioSlider';
import contract from './modules/contract';
import contractAdaptation from './modules/contractAdaptation';
import rewievsSlider from './modules/rewievsSlider';

menu();
smoothScroll();
modals();
phoneValidation();
test();
sendForm();
renderServiceList();
accordeonFAQ();
successFormulaHints();
repairTypesSlider();
portfolioSlider();
contract();
// contractAdaptation();
rewievsSlider();
